### PR TITLE
TypeScript: Convert `wp-story-editor` package

### LINKED ISSUE #12238: TypeScript: Convert `wp-story-editor` package
https://www.npmjs.com/package/wp-types could be useful for typing REST API responses.

### PR DESCRIPTION
**Pull request by spacedmonkey**
## To-do

- Fix tests. 
- Fix lint errors for @typescript-eslint/no-unsafe-argument
- Fix lint errors for @typescript-eslint/no-unsafe-call
- Fix lint errors for @typescript-eslint/no-unsafe-member-access
- Fix lint errors for @typescript-eslint/no-shadow
- Fix lint errors for 'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it  import/no-extraneous-dependencies

## Testing Instructions

- [ ] This is a non-user-facing change and requires no QA

This PR can be tested by following these steps:

1.

## Checklist

- [ ] This PR addresses an existing issue and I have linked this PR to it in ZenHub
- [ ] I have tested this code to the best of my abilities
- [ ] I have verified accessibility to the best of my abilities ([docs](https://github.com/googleforcreators/web-stories-wp/blob/main/docs/accessibility-testing.md))
- [ ] I have verified i18n and l10n (translation, right-to-left layout) to the best of my abilities
- [ ] This code is covered by automated tests (unit, integration, and/or e2e) to verify it works as intended ([docs](https://github.com/googleforcreators/web-stories-wp/tree/main/docs#testing))
- [ ] I have added documentation where necessary
- [ ] I have added a matching `Type: XYZ` label to the PR

---

Fixes #12238

### CODE REVIEW

**Comment by spacedmonkey** [comment]
There are currently 949 problems (947 errors, 2 warnings) errors. These can be broken in two 5 lints rules for 99% of the errors. These are. 

- @typescript-eslint/no-unsafe-argument
- @typescript-eslint/no-unsafe-call
- @typescript-eslint/no-unsafe-member-access
- @typescript-eslint/no-shadow
- 'react' should be listed in the project's dependencies. Run 'npm i -S react' to add it  import/no-extraneous-dependencies

This is a lot of work to fix these errors, I am not 100% that all these errors are valid and if we should even really be using these rules. Can some feedback and give me thoughts on next steps here.

File: packages/types/src/story/story.ts [hunk 1]
```diff
@@ -18,16 +18,34 @@
...
+  storyId: number;
+  author: {
+    id: number;
+    name: string;
+  };
+  content: string;
   version: number;
   pages: Page[];
+  autoAdvance: boolean;
+  defaultPageDuration: number;
```
Comment (spacedmonkey) [inline packages/types/src/story/story.ts]:
```suggestion
```

File: packages/url/src/addQueryArgs.ts [hunk 2]
```diff
@@ -27,7 +27,7 @@
  */
 export default function addQueryArgs(
   url: string,
-  args: Record<string, string>
+  args: Record<string, string|number>
```
Comment (spacedmonkey) [inline packages/url/src/addQueryArgs.ts]:
```suggestion
  args: Record<string, string>
```

**Comment by spacedmonkey** [comment]
After a rebase, this as generated some different and more errors. There are now interdepencies with stories-editor and design-system that generate errors.

**Comment by spacedmonkey** [comment]
So it looks like there are three dependencies that need to be converted to type script. 

```
Module '"@googleforcreators/design-system"' has no exported member 'BUTTON_SIZES'.
```
^  lots of these ( 52 x)
```
Cannot find module '@googleforcreators/story-editor' or its corresponding type declarations.
```
```
Module '"@googleforcreators/element-library"' has no exported member 'elementTypes'.
```

Let's revisit this PR after design system is covered over.

**Comment by spacedmonkey** [comment]
:(
